# Generated by Django 4.2.2 on 2023-06-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundZero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistaobra',
            name='nombreV',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
