# Generated by Django 4.2.2 on 2023-06-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundZero', '0002_vistaobra_nombrev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistaobra',
            name='imgVista',
            field=models.ImageField(upload_to='img/', verbose_name=' imgVista'),
        ),
        migrations.AlterField(
            model_name='vistaobra',
            name='nombreV',
            field=models.CharField(max_length=50, verbose_name='nombreV'),
        ),
    ]
