# Generated by Django 4.2.2 on 2023-06-30 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroundZero', '0004_artista_alter_vistaobra_imgvista_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artista',
        ),
    ]
