# Generated by Django 4.2.2 on 2023-07-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundZero', '0005_delete_artista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('idAr', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='idAr')),
                ('nombreAr', models.CharField(max_length=50, verbose_name='nombreAr')),
                ('apellidoAr', models.CharField(blank=True, max_length=50, null=True, verbose_name='apellidoAr')),
                ('fotoAr', models.ImageField(upload_to='img/', verbose_name='fotoAr')),
                ('descAr', models.CharField(max_length=250, verbose_name='descAr')),
                ('fechaIngr', models.DateField(verbose_name='fechaIgr')),
            ],
        ),
    ]
