# Generated by Django 4.2.2 on 2023-07-01 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroundZero', '0006_artista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artista',
            options={'ordering': ['nombreAr']},
        ),
    ]
