# Generated by Django 4.2.2 on 2023-07-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundZero', '0008_alter_artista_fotoar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='fotoAr',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='fotoAr'),
        ),
    ]
